---
assembly_info:
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  assembly_version: "{version}"
  file: "**\\AssemblyInfo.*"
  patch: true
branches:
  only:
    - master
before_build:
  - nuget restore
build:
  publish_nuget: true
  verbosity: normal
configuration: Release
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
  AppVeyorGlobalAPIToken:
    secure: XaWtuymf7dtXgjvEdnxXZVuIGVwMYUqOcE3dl3f3JzA=
  NugetAPIToken:
    secure: U630adFlFmWqwvorvfwA+YvFtAkfL+vw1EX0vCXbyk+R6qiLkIeqKek9yK+poBjV
image: "Visual Studio 2017"
nuget:
  disable_publish_on_pr: true
on_success:
  -
    ps: |
        if ( $env:APPVEYOR_REPO_TAG -And `
            ($env:APPVEYOR_REPO_TAG_NAME -match '^v\d+\.\d+\.\d+$') -And `
            ($env:APPVEYOR_REPO_BRANCH -eq 'master') -And `
            ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) ) # new version release
        {
          Write-Host "Pushing ${env:APPVEYOR_REPO_TAG_NAME} to NuGet feed"

          & "nuget" @("setApiKey", $env:NugetAPIToken)

          Get-ChildItem .\*.nupkg `
          | % { & "nuget" @("push", $_.FullName, `
                            "-Source", "https://www.nuget.org/api/v2/package") }
        }

        rm .\*.nupkg
version: "0.1.0.{build}"