name: Release .NET NuGet

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add github packages store as NuGet source
      run: |
        dotnet nuget update source github `
                                   --source https://nuget.pkg.github.com/aprismatic/index.json `
                                   --username "${{ github.actor }}" `
                                   --password "${{ github.token }}" `
                                   --configfile ./nuget.config
    - name: Restore packages
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --configuration Release --no-build

  publish:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add github packages store as NuGet source
      run: |
        dotnet nuget update source github `
                                   --source https://nuget.pkg.github.com/aprismatic/index.json `
                                   --username "${{ github.actor }}" `
                                   --password "${{ github.token }}" `
                                   --configfile ./nuget.config
    - name: Restore packages
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore -p:Version=${{ github.event.release.tag_name }}
    - name: Pack nuget packages
      run: dotnet pack --configuration Release --no-build --output nupkgs -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PackageVersion=${{ github.event.release.tag_name }}
    - name: Publish nuget packages
      run: dotnet nuget push **/*.nupkg --source "github" --skip-duplicate
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nupkgs
        path: nupkgs

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: nupkgs
        path: nupkgs
    - name: Release artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'nupkgs/*'
